### ISSUE TITLE
Peer-To-Peer code review 6/7/2020

### ISSUE THREAD

**Issue by mohapakram** [rahalrazika/online-shop#1]
* Recommended capitalizing text in CSS as it's easier to control from there.
* Commented on the overuse of important keyword.
* Asked the presenter to check for misspellings.
* Recommended centering text on mobile layout.
* Pointed some glitches in the layout especially on smaller screens.

Overall it's a great project! 
Keep up the GREAT work <3

**Comment by rahalrazika** [comment]
all comments have been considered
